# supabase/config.toml

project_id = "sklioimlyhomfemiruvb"

[api]
port = 54321

[db]
port = 54322

# Оставляем как есть
[functions.mock-tournament-ender]
enabled = true
verify_jwt = true
import_map = "./functions/mock-tournament-ender/deno.json"
entrypoint = "./functions/mock-tournament-ender/index.ts"

# 🔽 ДОБАВЬ ЭТОТ БЛОК
[functions."telegram-auth-callback"]
verify_jwt = false
entrypoint = "./functions/telegram-auth-callback/index.ts"
# import_map можно опустить, если не используешь deno.json тут
